[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
upload_speed = 921600

board_build.arduino.usb_mode = 1
board_build.arduino.usb_cdc_on_boot = 1

monitor_eol = LF
monitor_echo = yes
monitor_filters = send_on_enter

lib_deps =
  adafruit/Adafruit MPU6050
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit BusIO